### ISSUE TITLE
tuned configures are not installed in /user/local/lib

### ISSUE THREAD

**Issue by ce1adon** [ROCmSoftwarePlatform/MIOpenTensile#3]
The configures saved in yaml files are not installed in path /user/local/lib, which leads to tensile ICE issue"llvm::ErrorOr::storage_type *llvm::ErrorOr<std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> > >::getStorage() [T = std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >]: Assertion `!HasError && "Cannot get value when an error exists!"' failed."

**Comment by pfultz2** [comment]
This has been fixed on master.
